import BaseFont from '@/components/base/BaseFont';
import Footer from '@/components/layout/Footer';
import Header from '@/components/layout/Header';
import MainLayout from '@/components/layout/MainLayout';
import CoreProvider from '@/providers/CoreProvider';
import { cn } from '@/utils/cn';
import type { Metadata } from 'next';
import { Caveat, Inter } from 'next/font/google';

import '../styles/global.css';

const caveatFont = Caveat({
  variable: '--font-caveat',
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
  preload: true,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <BaseFont />
      </head>
      <body className={cn(caveatFont.variable)}>
        <CoreProvider>
          <Header />
          <MainLayout>{children}</MainLayout>
          <Footer />
        </CoreProvider>
      </body>
    </html>
  );
}
